name: VPS Test

on: [workflow_dispatch]

jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tools
        run: |
          sudo apt update
          sudo apt install -y neofetch
          neofetch
